### ISSUE TITLE
请教如何安装

### ISSUE THREAD

**Issue by isryanyhliu** [ryanh7/hacs-proxy#1]
大佬您好，想问下如何添加到ha中，方便说明一下or给个搜索关键字吗；
我搜了一圈都是教如何安装hacs的，没提到如何在hacs中安装自定义插件

**Comment by isryanyhliu** [comment]
我在 https://bbs.hassbian.com/thread-16136-1-1.html 这里，按照图片里搜索，没有搜到

**Comment by ryanh7** [comment]
https://hacs.xyz/docs/faq/custom_repositories/
