### ISSUE TITLE
取消`启用代理`失败

### ISSUE THREAD

**Issue by guanghwang** [ryanh7/hacs-proxy#3]
谢谢大佬的插件。

Bug的复现过程
1. 添加完代理，并启用。
2. 取消勾选“启用代理”，点击提交，HA界面打圈，与HA的连接断开。
3. 等待几分钟后，再次连上HA。启用代理依旧为勾取。

如有需要，我可以提供相关logs。目前不太确定哪些log与这个bug有关。

**Comment by s-leeq** [comment]
我这边也是同样的问题，但是即使开了调试模式，从始至终我都没发现HACS和这个插件的任何日志条目，非常诡异。

我的建议是禁用代理就直接在integration中删掉插件配置，用的时候再添加上（

**Comment by ryanh7** [comment]
v1.0.1已修复
